// LOCALHOST
###
GET http://localhost:8080/contacts/
###
GET http://localhost:8080/contacts/63ba4aa7de71fc903c458f83
###
GET http://localhost:8080/contacts/63ba4bbdde71fc903c458f84
###
GET http://localhost:8080/contacts/63ba4c01de71fc903c458f85

// PRODUCTION Deploy
###
GET https://chase-cse341.onrender.com/contacts/
###
GET https://chase-cse341.onrender.com/contacts/63ba4aa7de71fc903c458f83
###
GET https://chase-cse341.onrender.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://chase-cse341.onrender.com/contacts/622023f642f9ab4cd6e060b4
